on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute'
        type: string
        default: 'sleep 60'
        required: true

name: CommandTest

jobs:
  az-cli-test:
    runs-on: self-hosted
    steps:
    - name: Run command
      run: |
        ${{ github.event.inputs.command }}
        touch a.txt
    
    - name: Copy file
       # You may pin to the exact commit or the version.
       # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
      uses: canastro/copy-action@0.0.2
      with:
         # Source file
         source:  a.txt
         # Target file
         target: b.txt
